In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("googleplaystore.csv")
data

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [3]:
data.shape

(10841, 13)

In [4]:
for col in data.columns:
    print(col)

App
Category
Rating
Reviews
Size
Installs
Type
Price
Content Rating
Genres
Last Updated
Current Ver
Android Ver

In [5]:
p=data['Size'].value_counts()
p

Varies with device    1695
11M                    198
12M                    196
14M                    194
13M                    191
                      ...
526k                     1
176k                     1
992k                     1
412k                     1
74k                      1
Name: Size, Length: 462, dtype: int64

In [6]:
max(p)

1695

In [7]:
data.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

# Cleaning Data to perform operation

### Removing missing data

In [8]:
#Getting missing data
totalmissing=data.isnull().sum()
totalmissing

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [9]:
#removing missing data
data=data.dropna(how='any')
#getting missing data
data.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

### Cleaning Size Columns

In [10]:
#looking and working on size
pd.unique(data.Size)

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '5.5M', '17M', '39M', '31M',
       '4.2M', '23M', '6.0M', '6.1M', '4.6M', '9.2M', '5.2M', '11M',
       '24M', 'Varies with device', '9.4M', '15M', '10M', '1.2M', '26M',
       '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k', '3.6M', '5.7M',
       '8.6M', '2.4M', '27M', '2.7M', '2.5M', '7.0M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '22M', '6.4M', '3.2M', '8.2M', '4.9M', '9.5M', '5.0M',
       '5.9M', '13M', '73M', '6.8M', '3.5M', '4.0M', '2.3M', '2.1M',
       '42M', '9.1M', '55M', '23k', '7.3M', '6.5M', '1.5M', '7.5M', '51M',
       '41M', '48M', '8.5M', '46M', '8.3M', '4.3M', '4.7M', '3.3M', '40M',
       '7.8M', '8.8M', '6.6M', '5.1M', '61M', '66M', '79k', '8.4M',
       '3.7M', '118k', '44M', '695k', '1.6M', '6.2M', '53M', '1.4M',
       '3.0M', '7.2M', '5.8M', '3.8M', '9.6M', '45M', '63M', '49M', '77M',
       '4.4M', '70M', '9.3M', '8.1M', '36M', '6.9M', '7.4M', '84M', '97M',
       '2.0M', '1.9M', '1.8M', '5.3M', '47M', '556k', '526k', '76M',
       '7.6M', '59M', '9.7M', '78M', '72M', '43M', '7.7M', '6.3M', '334k',
       '93M', '65M', '79M', '100M', '58M', '50M', '68M', '64M', '34M',
       '67M', '60M', '94M', '9.9M', '232k', '99M', '624k', '95M', '8.5k',
       '41k', '292k', '80M', '1.7M', '10.0M', '74M', '62M', '69M', '75M',
       '98M', '85M', '82M', '96M', '87M', '71M', '86M', '91M', '81M',
       '92M', '83M', '88M', '704k', '862k', '899k', '378k', '4.8M',
       '266k', '375k', '1.3M', '975k', '980k', '4.1M', '89M', '696k',
       '544k', '525k', '920k', '779k', '853k', '720k', '713k', '772k',
       '318k', '58k', '241k', '196k', '857k', '51k', '953k', '865k',
       '251k', '930k', '540k', '313k', '746k', '203k', '26k', '314k',
       '239k', '371k', '220k', '730k', '756k', '91k', '293k', '17k',
       '74k', '14k', '317k', '78k', '924k', '818k', '81k', '939k', '169k',
       '45k', '965k', '90M', '545k', '61k', '283k', '655k', '714k', '93k',
       '872k', '121k', '322k', '976k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '306k', '175k', '350k', '383k', '454k',
       '1.0M', '70k', '812k', '442k', '842k', '417k', '412k', '459k',
       '478k', '335k', '782k', '721k', '430k', '429k', '192k', '460k',
       '728k', '496k', '816k', '414k', '506k', '887k', '613k', '778k',
       '683k', '592k', '186k', '840k', '647k', '373k', '437k', '598k',
       '716k', '585k', '982k', '219k', '55k', '323k', '691k', '511k',
       '951k', '963k', '25k', '554k', '351k', '27k', '82k', '208k',
       '551k', '29k', '103k', '116k', '153k', '209k', '499k', '173k',
       '597k', '809k', '122k', '411k', '400k', '801k', '787k', '50k',
       '643k', '986k', '516k', '837k', '780k', '20k', '498k', '600k',
       '656k', '221k', '228k', '176k', '34k', '259k', '164k', '458k',
       '629k', '28k', '288k', '775k', '785k', '636k', '916k', '994k',
       '309k', '485k', '914k', '903k', '608k', '500k', '54k', '562k',
       '847k', '948k', '811k', '270k', '48k', '523k', '784k', '280k',
       '24k', '892k', '154k', '18k', '33k', '860k', '364k', '387k',
       '626k', '161k', '879k', '39k', '170k', '141k', '160k', '144k',
       '143k', '190k', '376k', '193k', '473k', '246k', '73k', '253k',
       '957k', '420k', '72k', '404k', '470k', '226k', '240k', '89k',
       '234k', '257k', '861k', '467k', '676k', '552k', '582k', '619k'],
      dtype=object)

In [11]:
#getting number of app having size = varies with device
len(data[data.Size=='Varies with device'])

1637

In [12]:
# Converting varies with device to NA
data['Size'].replace('Varies with device',np.nan,inplace=True)
pd.unique(data.Size)

D:\anaconda1\lib\site-packages\pandas\core\series.py:4509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '5.5M', '17M', '39M', '31M',
       '4.2M', '23M', '6.0M', '6.1M', '4.6M', '9.2M', '5.2M', '11M',
       '24M', nan, '9.4M', '15M', '10M', '1.2M', '26M', '8.0M', '7.9M',
       '56M', '57M', '35M', '54M', '201k', '3.6M', '5.7M', '8.6M', '2.4M',
       '27M', '2.7M', '2.5M', '7.0M', '16M', '3.4M', '8.9M', '3.9M',
       '2.9M', '38M', '32M', '5.4M', '18M', '1.1M', '2.2M', '4.5M',
       '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M', '7.1M', '22M',
       '6.4M', '3.2M', '8.2M', '4.9M', '9.5M', '5.0M', '5.9M', '13M',
       '73M', '6.8M', '3.5M', '4.0M', '2.3M', '2.1M', '42M', '9.1M',
       '55M', '23k', '7.3M', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M',
       '8.5M', '46M', '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M',
       '8.8M', '6.6M', '5.1M', '61M', '66M', '79k', '8.4M', '3.7M',
       '118k', '44M', '695k', '1.6M', '6.2M', '53M', '1.4M', '3.0M',
       '7.2M', '5.8M', '3.8M', '9.6M', '45M', '63M', '49M', '77M', '4.4M',
       '70M', '9.3M', '8.1M', '36M', '6.9M', '7.4M', '84M', '97M', '2.0M',
       '1.9M', '1.8M', '5.3M', '47M', '556k', '526k', '76M', '7.6M',
       '59M', '9.7M', '78M', '72M', '43M', '7.7M', '6.3M', '334k', '93M',
       '65M', '79M', '100M', '58M', '50M', '68M', '64M', '34M', '67M',
       '60M', '94M', '9.9M', '232k', '99M', '624k', '95M', '8.5k', '41k',
       '292k', '80M', '1.7M', '10.0M', '74M', '62M', '69M', '75M', '98M',
       '85M', '82M', '96M', '87M', '71M', '86M', '91M', '81M', '92M',
       '83M', '88M', '704k', '862k', '899k', '378k', '4.8M', '266k',
       '375k', '1.3M', '975k', '980k', '4.1M', '89M', '696k', '544k',
       '525k', '920k', '779k', '853k', '720k', '713k', '772k', '318k',
       '58k', '241k', '196k', '857k', '51k', '953k', '865k', '251k',
       '930k', '540k', '313k', '746k', '203k', '26k', '314k', '239k',
       '371k', '220k', '730k', '756k', '91k', '293k', '17k', '74k', '14k',
       '317k', '78k', '924k', '818k', '81k', '939k', '169k', '45k',
       '965k', '90M', '545k', '61k', '283k', '655k', '714k', '93k',
       '872k', '121k', '322k', '976k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '306k', '175k', '350k', '383k', '454k',
       '1.0M', '70k', '812k', '442k', '842k', '417k', '412k', '459k',
       '478k', '335k', '782k', '721k', '430k', '429k', '192k', '460k',
       '728k', '496k', '816k', '414k', '506k', '887k', '613k', '778k',
       '683k', '592k', '186k', '840k', '647k', '373k', '437k', '598k',
       '716k', '585k', '982k', '219k', '55k', '323k', '691k', '511k',
       '951k', '963k', '25k', '554k', '351k', '27k', '82k', '208k',
       '551k', '29k', '103k', '116k', '153k', '209k', '499k', '173k',
       '597k', '809k', '122k', '411k', '400k', '801k', '787k', '50k',
       '643k', '986k', '516k', '837k', '780k', '20k', '498k', '600k',
       '656k', '221k', '228k', '176k', '34k', '259k', '164k', '458k',
       '629k', '28k', '288k', '775k', '785k', '636k', '916k', '994k',
       '309k', '485k', '914k', '903k', '608k', '500k', '54k', '562k',
       '847k', '948k', '811k', '270k', '48k', '523k', '784k', '280k',
       '24k', '892k', '154k', '18k', '33k', '860k', '364k', '387k',
       '626k', '161k', '879k', '39k', '170k', '141k', '160k', '144k',
       '143k', '190k', '376k', '193k', '473k', '246k', '73k', '253k',
       '957k', '420k', '72k', '404k', '470k', '226k', '240k', '89k',
       '234k', '257k', '861k', '467k', '676k', '552k', '582k', '619k'],
      dtype=object)

In [13]:
#removing K and M from last of size and converting to float
a=data.Size.replace(r'[kM]+$','',regex=True).astype(float) 
#converting K to 10**3 and M to 10**6
b=data.Size.str.extract(r'[\d\.]+([kM]+)',expand=False).fillna(1).replace(['k','M'],[10**3,10**6]).astype(int)

In [14]:
#get size in bytes
data.Size=a*b

D:\anaconda1\lib\site-packages\pandas\core\generic.py:5494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [15]:
#filling all NaN value with mean
data['Size'].fillna(data.groupby('Category')['Size'].transform('mean'),inplace = True)

D:\anaconda1\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [16]:
pd.unique(data.Size)# after removing K and M

array([1.90000000e+07, 1.40000000e+07, 8.70000000e+06, 2.50000000e+07,
       2.80000000e+06, 5.60000000e+06, 2.90000000e+07, 3.30000000e+07,
       3.10000000e+06, 2.80000000e+07, 1.20000000e+07, 2.00000000e+07,
       2.10000000e+07, 3.70000000e+07, 5.50000000e+06, 1.70000000e+07,
       3.90000000e+07, 3.10000000e+07, 4.20000000e+06, 2.30000000e+07,
       6.00000000e+06, 6.10000000e+06, 4.60000000e+06, 9.20000000e+06,
       5.20000000e+06, 1.10000000e+07, 2.40000000e+07, 1.29396552e+07,
       9.40000000e+06, 1.50000000e+07, 1.00000000e+07, 1.20000000e+06,
       2.60000000e+07, 8.00000000e+06, 7.90000000e+06, 5.60000000e+07,
       5.70000000e+07, 2.15412857e+07, 3.50000000e+07, 5.40000000e+07,
       2.01000000e+05, 3.60000000e+06, 5.70000000e+06, 8.60000000e+06,
       2.40000000e+06, 2.70000000e+07, 2.70000000e+06, 2.50000000e+06,
       7.00000000e+06, 1.60000000e+07, 3.40000000e+06, 8.90000000e+06,
       3.90000000e+06, 2.90000000e+06, 3.80000000e+07, 3.20000000e+07,
       5.40000000e+06, 1.80000000e+07, 1.10000000e+06, 2.20000000e+06,
       4.50000000e+06, 9.80000000e+06, 1.55135135e+07, 5.20000000e+07,
       9.00000000e+06, 6.70000000e+06, 3.00000000e+07, 2.60000000e+06,
       7.10000000e+06, 2.20000000e+07, 6.40000000e+06, 3.20000000e+06,
       8.20000000e+06, 1.43862500e+07, 4.90000000e+06, 9.50000000e+06,
       5.00000000e+06, 5.90000000e+06, 1.30000000e+07, 7.30000000e+07,
       6.80000000e+06, 3.50000000e+06, 4.00000000e+06, 2.30000000e+06,
       2.10000000e+06, 4.20000000e+07, 1.49117236e+07, 9.10000000e+06,
       5.50000000e+07, 2.30000000e+04, 7.30000000e+06, 6.50000000e+06,
       1.50000000e+06, 7.50000000e+06, 5.10000000e+07, 4.10000000e+07,
       4.80000000e+07, 8.50000000e+06, 4.60000000e+07, 1.31582245e+07,
       8.30000000e+06, 4.30000000e+06, 4.70000000e+06, 3.30000000e+06,
       4.00000000e+07, 7.80000000e+06, 1.24583081e+07, 8.80000000e+06,
       6.60000000e+06, 5.10000000e+06, 6.10000000e+07, 6.60000000e+07,
       7.90000000e+04, 8.40000000e+06, 3.70000000e+06, 1.18000000e+05,
       4.40000000e+07, 6.95000000e+05, 1.60000000e+06, 1.83127168e+07,
       6.20000000e+06, 5.30000000e+07, 1.40000000e+06, 3.00000000e+06,
       7.20000000e+06, 5.80000000e+06, 3.80000000e+06, 9.60000000e+06,
       4.50000000e+07, 6.30000000e+07, 4.90000000e+07, 7.70000000e+07,
       4.40000000e+06, 7.00000000e+07, 9.30000000e+06, 8.10000000e+06,
       3.60000000e+07, 2.07616545e+07, 6.90000000e+06, 7.40000000e+06,
       8.40000000e+07, 9.70000000e+07, 2.00000000e+06, 1.90000000e+06,
       1.80000000e+06, 5.30000000e+06, 4.70000000e+07, 5.56000000e+05,
       5.26000000e+05, 7.60000000e+07, 7.60000000e+06, 5.90000000e+07,
       2.18533333e+07, 9.70000000e+06, 7.80000000e+07, 7.20000000e+07,
       4.30000000e+07, 7.70000000e+06, 6.30000000e+06, 1.44324737e+07,
       3.34000000e+05, 1.85931203e+07, 9.30000000e+07, 6.50000000e+07,
       7.90000000e+07, 1.00000000e+08, 5.80000000e+07, 5.00000000e+07,
       6.80000000e+07, 2.41630952e+07, 6.40000000e+07, 3.40000000e+07,
       2.42377130e+07, 6.70000000e+07, 6.00000000e+07, 9.40000000e+07,
       9.90000000e+06, 1.75053571e+07, 1.27013033e+07, 2.32000000e+05,
       9.90000000e+07, 6.24000000e+05, 9.50000000e+07, 8.50000000e+03,
       4.10000000e+04, 2.92000000e+05, 8.00000000e+07, 1.70000000e+06,
       1.53711500e+07, 7.40000000e+07, 4.53406057e+07, 6.20000000e+07,
       6.90000000e+07, 7.50000000e+07, 9.80000000e+07, 8.50000000e+07,
       8.20000000e+07, 9.60000000e+07, 8.70000000e+07, 7.10000000e+07,
       8.60000000e+07, 9.10000000e+07, 8.10000000e+07, 9.20000000e+07,
       8.30000000e+07, 8.80000000e+07, 3.01628119e+07, 7.04000000e+05,
       1.94148272e+07, 8.62000000e+05, 8.99000000e+05, 3.78000000e+05,
       4.80000000e+06, 2.66000000e+05, 3.75000000e+05, 1.30000000e+06,
       9.75000000e+05, 9.80000000e+05, 1.91701243e+07, 4.10000000e+06,
       8.90000000e+07, 1.71118324e+07, 1.75992542e+07, 2.65068947e+07,
       2.52451125e+07, 8.29102054e+06, 6.96000000e+05, 5.44000000e+05,
       5.25000000e+05, 1.16687014e+07, 9.20000000e+05, 7.79000000e+05,
       8.53000000e+05, 1.28996426e+07, 7.20000000e+05, 7.13000000e+05,
       2.15795455e+07, 1.34055294e+07, 1.61644828e+07, 1.31278580e+07,
       1.74488421e+07, 7.72000000e+05, 3.18000000e+05, 5.80000000e+04,
       2.41000000e+05, 1.96000000e+05, 8.57000000e+05, 5.10000000e+04,
       9.53000000e+05, 8.65000000e+05, 2.51000000e+05, 9.30000000e+05,
       5.40000000e+05, 3.13000000e+05, 7.46000000e+05, 2.03000000e+05,
       2.60000000e+04, 3.14000000e+05, 2.39000000e+05, 3.71000000e+05,
       2.20000000e+05, 7.30000000e+05, 7.56000000e+05, 9.10000000e+04,
       2.93000000e+05, 1.70000000e+04, 7.40000000e+04, 1.40000000e+04,
       3.17000000e+05, 7.80000000e+04, 9.24000000e+05, 8.18000000e+05,
       8.10000000e+04, 9.39000000e+05, 1.69000000e+05, 4.50000000e+04,
       9.65000000e+05, 9.00000000e+07, 5.45000000e+05, 6.10000000e+04,
       2.83000000e+05, 6.55000000e+05, 7.14000000e+05, 9.30000000e+04,
       8.72000000e+05, 1.21000000e+05, 3.22000000e+05, 9.76000000e+05,
       2.06000000e+05, 9.54000000e+05, 4.44000000e+05, 7.17000000e+05,
       2.10000000e+05, 6.09000000e+05, 3.08000000e+05, 3.06000000e+05,
       1.75000000e+05, 3.50000000e+05, 3.83000000e+05, 4.54000000e+05,
       1.00000000e+06, 7.00000000e+04, 8.12000000e+05, 4.42000000e+05,
       8.42000000e+05, 4.17000000e+05, 4.12000000e+05, 4.59000000e+05,
       4.78000000e+05, 3.35000000e+05, 7.82000000e+05, 7.21000000e+05,
       4.30000000e+05, 4.29000000e+05, 1.92000000e+05, 4.60000000e+05,
       7.28000000e+05, 4.96000000e+05, 8.16000000e+05, 4.14000000e+05,
       5.06000000e+05, 8.87000000e+05, 6.13000000e+05, 7.78000000e+05,
       6.83000000e+05, 5.92000000e+05, 1.86000000e+05, 8.40000000e+05,
       6.47000000e+05, 3.73000000e+05, 4.37000000e+05, 5.98000000e+05,
       7.16000000e+05, 5.85000000e+05, 9.82000000e+05, 2.19000000e+05,
       5.50000000e+04, 3.23000000e+05, 6.91000000e+05, 5.11000000e+05,
       9.51000000e+05, 9.63000000e+05, 2.50000000e+04, 5.54000000e+05,
       3.51000000e+05, 2.70000000e+04, 8.20000000e+04, 2.08000000e+05,
       5.51000000e+05, 2.90000000e+04, 1.03000000e+05, 1.16000000e+05,
       1.53000000e+05, 2.09000000e+05, 4.99000000e+05, 1.73000000e+05,
       5.97000000e+05, 8.09000000e+05, 1.22000000e+05, 4.11000000e+05,
       4.00000000e+05, 8.01000000e+05, 7.87000000e+05, 5.00000000e+04,
       6.43000000e+05, 9.86000000e+05, 5.16000000e+05, 8.37000000e+05,
       7.80000000e+05, 2.00000000e+04, 4.98000000e+05, 6.00000000e+05,
       6.56000000e+05, 2.21000000e+05, 2.28000000e+05, 1.76000000e+05,
       3.40000000e+04, 2.59000000e+05, 1.64000000e+05, 4.58000000e+05,
       6.29000000e+05, 2.80000000e+04, 2.88000000e+05, 7.75000000e+05,
       7.85000000e+05, 6.36000000e+05, 9.16000000e+05, 9.94000000e+05,
       3.09000000e+05, 4.85000000e+05, 9.14000000e+05, 9.03000000e+05,
       6.08000000e+05, 5.00000000e+05, 5.40000000e+04, 5.62000000e+05,
       8.47000000e+05, 9.48000000e+05, 8.11000000e+05, 2.70000000e+05,
       4.80000000e+04, 5.23000000e+05, 7.84000000e+05, 2.80000000e+05,
       2.40000000e+04, 8.92000000e+05, 1.54000000e+05, 1.80000000e+04,
       3.30000000e+04, 8.60000000e+05, 3.64000000e+05, 3.87000000e+05,
       6.26000000e+05, 1.61000000e+05, 8.79000000e+05, 3.90000000e+04,
       1.70000000e+05, 1.41000000e+05, 1.60000000e+05, 1.44000000e+05,
       1.43000000e+05, 1.90000000e+05, 3.76000000e+05, 1.93000000e+05,
       4.73000000e+05, 2.46000000e+05, 7.30000000e+04, 2.53000000e+05,
       9.57000000e+05, 4.20000000e+05, 7.20000000e+04, 4.04000000e+05,
       4.70000000e+05, 2.26000000e+05, 2.40000000e+05, 8.90000000e+04,
       2.34000000e+05, 2.57000000e+05, 8.61000000e+05, 4.67000000e+05,
       6.76000000e+05, 5.52000000e+05, 5.82000000e+05, 6.19000000e+05])

### Cleaning Installs Columns

In [17]:
pd.unique(data.Installs)

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '100+', '500+', '10+',
       '5+', '50+', '1+'], dtype=object)

In [18]:
#Removing + and convertin from object to int data type
data.Installs=data.Installs.replace(r'[,+]','',regex=True).astype(int)
pd.unique(data.Installs)

array([     10000,     500000,    5000000,   50000000,     100000,
            50000,    1000000,   10000000,       5000,  100000000,
       1000000000,       1000,  500000000,        100,        500,
               10,          5,         50,          1])

In [19]:
sorted_data=sorted(list(data['Installs'].unique()))
data['Installforplot']=data['Installs'].replace(sorted_data,range(0,len(sorted_data),1))

<ipython-input-19-6bf455ef885c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Installforplot']=data['Installs'].replace(sorted_data,range(0,len(sorted_data),1))

In [20]:
p=data.Installforplot
#s=sorted(p)
#s
p.head(20)

0      8
1     11
2     13
3     15
4     10
5      9
6      9
7     12
8     12
9      8
10    12
11    12
12    14
13    10
14    10
16    11
17     8
18    13
19    14
20    10
Name: Installforplot, dtype: int64

In [22]:
data[data.Installs.gt(data.Installs.quantile(0.9))]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installforplot
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,2.500000e+07,50000000,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,15
139,Wattpad 📖 Free Books,BOOKS_AND_REFERENCE,4.6,2914724,1.438625e+07,100000000,Free,0,Teen,Books & Reference,"August 1, 2018",Varies with device,Varies with device,16
143,Amazon Kindle,BOOKS_AND_REFERENCE,4.2,814080,1.438625e+07,100000000,Free,0,Teen,Books & Reference,"July 27, 2018",Varies with device,Varies with device,16
152,Google Play Books,BOOKS_AND_REFERENCE,3.9,1433233,1.438625e+07,1000000000,Free,0,Teen,Books & Reference,"August 3, 2018",Varies with device,Varies with device,18
188,Indeed Job Search,BUSINESS,4.3,674730,1.491172e+07,50000000,Free,0,Everyone,Business,"May 21, 2018",Varies with device,Varies with device,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10429,Talking Tom Bubble Shooter,FAMILY,4.4,687136,5.400000e+07,50000000,Free,0,Everyone,Casual,"May 25, 2018",1.5.3.20,4.1 and up,15
10513,Flight Simulator: Fly Plane 3D,FAMILY,4.0,660613,2.100000e+07,50000000,Free,0,Everyone,Simulation,"March 1, 2017",1.32,2.3 and up,15
10549,Toy Truck Rally 3D,GAME,4.0,301895,2.500000e+07,50000000,Free,0,Everyone,Racing,"May 23, 2018",1.4.4,4.1 and up,15
10647,Motorola FM Radio,VIDEO_PLAYERS,3.9,54815,1.616448e+07,100000000,Free,0,Everyone,Video Players & Editors,"May 2, 2018",Varies with device,Varies with device,16
10707,Photo Editor Collage Maker Pro,PHOTOGRAPHY,4.5,1519671,1.759925e+07,100000000,Free,0,Everyone,Photography,"February 1, 2018",Varies with device,Varies with device,16

### Cleaning Price Columns

In [23]:
data.Price.value_counts().head(20)

0          8715
$2.99       114
$0.99       106
$4.99        70
$1.99        59
$3.99        58
$1.49        30
$2.49        21
$5.99        18
$9.99        16
$6.99        13
$399.99      11
$14.99       10
$4.49         9
$7.99         7
$3.49         7
$29.99        6
$11.99        5
$24.99        5
$19.99        5
Name: Price, dtype: int64

In [24]:
#Removing doller sign
data.Price=data.Price.replace(r'[,$]','',regex=True).astype(float)

D:\anaconda1\lib\site-packages\pandas\core\generic.py:5494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [25]:
data.Price.describe()

count    9360.000000
mean        0.961279
std        15.821640
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       400.000000
Name: Price, dtype: float64

In [26]:
#App Having Maximum Price
data[data.Price==400]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installforplot
4367,I'm Rich - Trump Edition,LIFESTYLE,3.6,275,7300000.0,10000,Paid,400.0,Everyone,Lifestyle,"May 3, 2018",1.0.1,4.1 and up,8

In [27]:
#Last Updation
data['Last Updated']=pd.to_datetime(data['Last Updated'])

<ipython-input-27-581970609bc2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Last Updated']=pd.to_datetime(data['Last Updated'])

### Number of apps in each categories

In [28]:

total=data.Category.value_counts()
percent=(data.Category.value_counts()/data.Category.notnull().sum())*100
category_data=pd.concat([total,percent],axis=1,keys=['total','percent'])
category_data

                     total    percent
FAMILY                1746  18.653846
GAME                  1097  11.720085
TOOLS                  733   7.831197
PRODUCTIVITY           351   3.750000
MEDICAL                350   3.739316
COMMUNICATION          328   3.504274
FINANCE                323   3.450855
SPORTS                 319   3.408120
PHOTOGRAPHY            317   3.386752
LIFESTYLE              314   3.354701
PERSONALIZATION        312   3.333333
BUSINESS               303   3.237179
HEALTH_AND_FITNESS     297   3.173077
SOCIAL                 259   2.767094
SHOPPING               238   2.542735
NEWS_AND_MAGAZINES     233   2.489316
TRAVEL_AND_LOCAL       226   2.414530
DATING                 195   2.083333
BOOKS_AND_REFERENCE    178   1.901709
VIDEO_PLAYERS          160   1.709402
EDUCATION              155   1.655983
ENTERTAINMENT          149   1.591880
MAPS_AND_NAVIGATION    124   1.324786
FOOD_AND_DRINK         109   1.164530
HOUSE_AND_HOME          76   0.811966
WEATHER                 75   0.801282
AUTO_AND_VEHICLES       73   0.779915
LIBRARIES_AND_DEMO      64   0.683761
ART_AND_DESIGN          61   0.651709
COMICS                  58   0.619658
PARENTING               50   0.534188
EVENTS                  45   0.480769
BEAUTY                  42   0.448718

In [29]:
data['Last Updated']=pd.to_datetime(data['Last Updated'])
data

<ipython-input-29-dc8133ac1df2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Last Updated']=pd.to_datetime(data['Last Updated'])

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installforplot
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000000.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,8
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,11
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8700000.0,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,13
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000000.0,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,15
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800000.0,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2600000.0,500,Free,0.0,Everyone,Education,2017-06-18,1.0.0,4.1 and up,5
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53000000.0,5000,Free,0.0,Everyone,Education,2017-07-25,1.48,4.1 and up,7
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3600000.0,100,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1 and up,4
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,14386250.0,1000,Free,0.0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,6
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19000000.0,10000000,Free,0.0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,14

In [30]:
#Exporting Cleaned data for use it at another place like tableau
data.to_csv('data-filtered.csv')

In [43]:

test = data.sort_values(['Installs'], ascending=[True])
test.head(100)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installforplot
10697,Mu.F.O.,GAME,5.0,2,16000000.0,1,Paid,0.99,Everyone,Arcade,2017-03-03,1.0,2.3 and up,0
5917,Ra Ga Ba,GAME,5.0,2,20000000.0,1,Paid,1.49,Everyone,Arcade,2017-02-08,1.0.4,2.3 and up,0
2454,KBA-EZ Health Guide,MEDICAL,5.0,4,25000000.0,1,Free,0.00,Everyone,Medical,2018-08-02,1.0.72,4.0.3 and up,0
2459,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.0,1,4600000.0,5,Free,0.00,Everyone,Medical,2018-08-02,2.0,4.0 and up,1
10562,FK Atlantas,SPORTS,1.5,2,26000000.0,5,Free,0.00,Everyone,Sports,2018-02-21,1.0,4.1 and up,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5151,Clarksburg AH,MEDICAL,1.0,1,28000000.0,50,Free,0.00,Everyone,Medical,2017-05-01,300000.0.81,4.0.3 and up,3
4553,R File Manager,TOOLS,4.8,17,6700000.0,50,Free,0.00,Everyone,Tools,2018-05-05,v2,4.4 and up,3
6363,Read it easy for BK,LIFESTYLE,5.0,1,3200000.0,50,Free,0.00,Everyone,Lifestyle,2018-07-15,1.2,4.1 and up,3
8212,Scale Models DB,TOOLS,4.4,9,33000000.0,50,Paid,2.99,Everyone,Tools,2018-05-03,0.6.2,4.3 and up,3
8875,DT future1 cam,TOOLS,1.0,1,24000000.0,50,Free,0.00,Everyone,Tools,2018-03-27,3.1,2.2 and up,3

In [74]:
test = data[["App","Reviews","Installs"]]
test

                                                     App Reviews  Installs
0         Photo Editor & Candy Camera & Grid & ScrapBook     159     10000
1                                    Coloring book moana     967    500000
2      U Launcher Lite – FREE Live Cool Themes, Hide ...   87510   5000000
3                                  Sketch - Draw & Paint  215644  50000000
4                  Pixel Draw - Number Art Coloring Book     967    100000
...                                                  ...     ...       ...
10834                                      FR Calculator       7       500
10836                                   Sya9a Maroc - FR      38      5000
10837                   Fr. Mike Schmitz Audio Teachings       4       100
10839                      The SCP Foundation DB fr nn5n     114      1000
10840      iHoroscope - 2018 Daily Horoscope & Astrology  398307  10000000

[9360 rows x 3 columns]

In [78]:
test = test.sort_values(['Installs'], ascending=[False])
test.head(1000)

                                               App   Reviews    Installs
451                                          Gmail   4604483  1000000000
3765                                   Google News    877635  1000000000
2853                                 Google Photos  10858538  1000000000
382       Messenger – Text and Video Chat for Free  56646578  1000000000
386                                       Hangouts   3419433  1000000000
...                                            ...       ...         ...
2651  Waplog - Free Chat, Dating App, Meet Singles    522018    10000000
2598                    Tapatalk - 100,000+ Forums    285816    10000000
2631                                         LOVOO    852455    10000000
2632              Jaumo Dating, Flirt & Live Video    900064    10000000
2637                   textPlus: Free Text & Calls    382121    10000000

[1000 rows x 3 columns]